### ISSUE TITLE
[Discussion] A way Brands can talk to influencers

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#3]
- Brand will send a request to influencers.
- influencer will accept it.
- Brand will have to pay a verification charge to make sure its a genuine brand
- Then they can communicate over the platform using a message box.

How can this be implemented in the platform

**Comment by Hemu21** [comment]
Does we need to create the proposal overview in the pr for this?

**Comment by Kajol-Kumari** [comment]
Its more like proposing the solution, should we create our own messaging service or should we integrate with any free available bot

**Comment by Hemu21** [comment]
@Kajol-Kumari  With considering all the aspects. I had found a solution for this. We can create a collection to store the requests with fields brand_Id, user_id, request status, time stamp. user is able to accept the request. we use any payment gatway integration for paying money. If user accepted and the brand is genuine then they can communicate. For that communication I suggest to build our own messaging service using socket.Io why because currently we are investing money on rapid api. we need to consider the budget also. It is a open source so contributor will take care of building it. after launching the app based upon the responses. we can update the app. then we can update the our messaging service or we can use available messaging services like Twilio Programmable Chat etc. So we can take the benefits of opensource and make the app successful. 

I hope you like this plan. Please tell me you opinion.

**Comment by Kajol-Kumari** [comment]
hmm, i am also tending to create our own messaging service, but If we go ahead with this approach then task bifcurcation of the tasks, can you share what should be the action items in sequence here?

**Comment by Hemu21** [comment]
**This is for messaging service:**
1. Database Schema: Set up collections for users, messages, and conversations.
2. WebSocket Server: Implement real-time communication with Socket.IO.
3. Message Storage: Store and retrieve messages in MongoDB.
4. API Server: Develop endpoints for message and conversation management.
5. Frontend Integration: Build a user interface for messaging and integrate WebSocket.

_1. Collections_

- Users: Stores user profiles.
   - Fields: userId, name, email, userType (brand, influencer), verificationStatus
- Messages: Stores chat messages.
   - Fields: messageId, senderId, receiverId, content, timestamp
- Conversations: Manages conversations between users.
   - Fields: conversationId, participants (array of userIds), lastMessageId, updatedAt

_Set Up WebSocket Server_
**Steps**

- Initialize Server: Use Socket.IO with a Node.js server.
- Authenticate Users: Validate WebSocket connections with user authentication tokens.
- Manage Connections: Keep track of connected users and their socket IDs for real-time message delivery.
- Handle Events:
  - connect: Authenticate and register user.
  - disconnect: Clean up user connection data.
  - message: Handle incoming messages and broadcast to recipients.

_Implement Message Storage and Retrieval_
**Steps**

Message Storage:

- On receiving a message, store it in the Messages collection.
- Update the corresponding conversation in the Conversations collection.

Message Retrieval:

- Create an API endpoint to fetch conversation history.
- Use pagination for efficient data retrieval.


@Kajol-Kumari  This is a overview with actions items in sequence. If it is ok then let me know. I will create pr as it is a discussion of level1.

**Comment by Kajol-Kumari** [comment]
hmm, granularity is still missing but yeah, good way to start, you can document it in a markdown file with issue bifurcation in the same file and raise the pr
